### PR TITLE
Update index.ts

### PR DESCRIPTION
**Pull request by nicholasareed**
Fix first render

### CODE REVIEW

**Comment by jpalumickas** [comment]
Hey @nicholasareed 

We had like this before but in https://github.com/jpalumickas/use-window-focus/pull/5 PR, SSR support was added.

**Comment by nicholasareed** [comment]
switched to checking for existence of `document`, which should both solve SSR issues and provide correct first-render behavior.

**Comment by nicholasareed** [comment]
Actually, I dont know if `document && ...` fixes the issue. Reading more about the SSR problems it sounds like `document` won't even exist, so it might need to be
```
const [focused, setFocused] = useState(() => typeof document !== 'undefined' && document.hasFocus());
```
I can probably try it out in an temporary SSR environment.

**Comment by jpalumickas** [comment]
Hey @nicholasareed,
Did you have time to check if it is working on SSR?

**Comment by nicholasareed** [comment]
@jpalumickas ^

**Comment by jpalumickas** [comment]
@nicholasareed thanks, merged. Also, I changed a little bit focus/blur event to fix tests. I released 1.3.0 version, can you test if it's working for you?

**Comment by nicholasareed** [comment]
@jpalumickas thanks! sorry I completely forgot to modify tests 😬  seems great!

**Pull request merged**
